source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyUnwrap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'

  # Pods for MyUnwrap

end
