# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NeteaseCloudMusic-homepage-swift' do
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher'
  pod 'SnapKit'
end
