# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target '无限滚动' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'
  # Pods for 无限滚动

end
